### ISSUE TITLE
Mejorar programas

### ISSUE THREAD

**Issue by dawagja** [Ramirez9/Entornos_2#2]
Hola Fran, deberías crear un método para mostrar el resultado en cada uno de los programas que tienes e invocarlo en el main.

https://github.com/Ramirez9/Entornos_2/blob/master/Expresiones/AreaCirculo.java#L17
```java
private void imprimirResultado(double area){
		System.out.println("El area del circulo es: "+area);
}

```

**Comment by Ramirez9** [comment]
Oh, tomaré su decisión con detenimiento

Muchas gracias, muy amable.
